<?php
/**
 * @file
 * structure.features.uuid_fpp.inc
 */

/**
 * Implements hook_uuid_features_default_fpps().
 */
function structure_uuid_features_default_fpps() {
  $fpps = array();

  $fpps[] = array(
    'timestamp' => 1417745560,
    'title' => '@gladstonelabs',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => '@gladstonelabs twitter feed',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417744569,
    'uuid' => '23688efa-ef09-4a7d-9052-41c870c65040',
    'language' => 'und',
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => '<a class="twitter-timeline"
  href="https://twitter.com/gladstonelabs"
  data-widget-id="516743444740337664"
  data-screen-name="gladstonelabs"
  data-link-color="#0c4a6"
  data-border-color="#0c4a6"
  height="362px"
  data-chrome="noheader nofooter noborders noscrollbar transparent"
  data-show-replies="false"
></a>',
          'format' => 'php_code',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418087860,
    'title' => 'SCIENTIST SPOTLIGHT',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Scientist Spotlight',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417733712,
    'uuid' => '25f3cd3d-3153-4561-844d-b3ae9ffeee19',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => '<p><b>BENOIT BRUNEAU, PHD</b><br />
Mapping the heart, moving<br />
closer to heart disease cures</p>
',
          'format' => 'limited_html',
          'safe_value' => '<p><b>BENOIT BRUNEAU, PHD</b><br />
Mapping the heart, moving<br />
closer to heart disease cures</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418944532,
    'title' => 'OUR NEWSLETTER',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => 'Our Newsletter',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1418779993,
    'uuid' => '41828720-2301-4275-9f6e-3c486397c1f0',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Important discoveries and 
insights, direct to your inbox',
          'format' => 'rich_text',
          'safe_value' => '<p>Important discoveries and<br />
insights, direct to your inbox</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'http://lb.benchmarkemail.com//listbuilder/signupnew?9bGwlFuGOREK7yW8HfQ6A3TVLJ38FkWyBw1WHzVrH8T5mj5OqPbK3uMzIjNtMjwz',
          'title' => 'SIGN UP',
          'attributes' => array(
            'class' => '',
          ),
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418944508,
    'title' => 'FEATURED VIDEO',
    'log' => '',
    'bundle' => 'image',
    'link' => 1,
    'path' => 'https://www.youtube.com/watch?v=tAjtoYRXm84',
    'reusable' => 1,
    'admin_title' => 'Featured Video',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734507,
    'uuid' => '430d4112-be9c-4653-956a-645ab9ddbf9c',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'BETTER COGNITION SEEN 
WITH GENE VARIANT 
CARRIED BY 1 IN 5',
          'format' => 'rich_text',
          'safe_value' => '<p>BETTER COGNITION SEEN<br />
WITH GENE VARIANT<br />
CARRIED BY 1 IN 5</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418615300,
    'title' => 'OUR MISSION',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Our Mission',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734598,
    'uuid' => '6d4bd53f-a154-470d-8ed5-ccea06f9e0ca',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Use visionary science and 
technology to overcome
major unsolved diseases',
          'format' => 'rich_text',
          'safe_value' => '<p>Use visionary science and<br />
technology to overcome<br />
major unsolved diseases</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'content/mission-and-presidents-vision',
          'title' => 'LEARN MORE',
          'attributes' => array(
            'class' => '',
          ),
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418251664,
    'title' => '',
    'log' => '',
    'bundle' => 'map',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => 'Map-2',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1418251664,
    'uuid' => '84b751b0-6c79-4f3f-ab16-6331be1374b0',
    'language' => 'und',
    'field_longtext' => array(),
    'field_map_address' => array(
      'und' => array(
        0 => array(
          'value' => '1650 Owens Street San Francisco, CA 94158-2261',
          'format' => NULL,
          'safe_value' => '1650 Owens Street San Francisco, CA 94158-2261',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418615386,
    'title' => 'GET OUR NEWSLETTER',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Get Our Newsletter',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734677,
    'uuid' => '8ec939f2-35ae-4d63-929b-00c890ea51ab',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'file_rendered',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Important discoveries and 
insights, direct to your inbox',
          'format' => 'rich_text',
          'safe_value' => '<p>Important discoveries and<br />
insights, direct to your inbox</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418954586,
    'title' => '',
    'log' => '',
    'bundle' => 'image',
    'link' => 1,
    'path' => 'http://today.gladstone.internal:88/current/builds/gs5alpha2/about-us/pressroom/news/gladstone-scientist-elected-aaas',
    'reusable' => 1,
    'admin_title' => 'Front page feature',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734389,
    'uuid' => '91b7243d-de5b-4eb2-a789-562a48273cbb',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(),
  );
  $fpps[] = array(
    'timestamp' => 1418669520,
    'title' => 'OUR SCIENCE',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Our Science',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417733879,
    'uuid' => 'c9a58689-7b2b-4f2d-8109-6b421f765214',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'file_rendered',
          'settings' => 'a:0:{}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Focused on unsolved
diseases with profound
medical, economic, and
social impact',
          'format' => 'rich_text',
          'safe_value' => '<p>Focused on unsolved<br />
diseases with profound<br />
medical, economic, and<br />
social impact</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'institute/gind/home/67',
          'title' => 'BRAIN',
          'attributes' => array(
            'class' => '',
          ),
        ),
        1 => array(
          'url' => 'institute/gicd/home/88',
          'title' => 'HEART',
          'attributes' => array(
            'class' => '',
          ),
        ),
        2 => array(
          'url' => 'institute/givi/home/82',
          'title' => 'IMMUNESYSTEM',
          'attributes' => array(
            'class' => '',
          ),
        ),
        3 => array(
          'url' => 'institute/stem%20cell/home/18',
          'title' => 'STEM CELL',
          'attributes' => array(
            'class' => '',
          ),
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418776870,
    'title' => 'LOREM IPSUM',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Lorem Ipsum',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734803,
    'uuid' => 'd6dbded7-1639-4f46-8cb6-32a0de08c7cc',
    'language' => 'und',
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => '<p style="font-size:1.1em;">&nbsp;<br />
&nbsp;<br />
&nbsp;<br />
<font style="font-size:1.0em;">&nbsp;</font><br />
&nbsp;</p>
',
          'format' => 'limited_html',
          'safe_value' => '<p style="font-size:1.1em;"> <br />
 <br />
 <br /><font style="font-size:1em;"> </font><br />
 </p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418249598,
    'title' => '',
    'log' => '',
    'bundle' => 'map',
    'link' => 0,
    'path' => '',
    'reusable' => 0,
    'admin_title' => 'Map-1',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1418249598,
    'uuid' => 'e0259bb4-cfce-48ca-9d39-9b3e85803bc8',
    'language' => 'und',
    'field_longtext' => array(),
    'field_map_address' => array(
      'und' => array(
        0 => array(
          'value' => '1650 Owens Street San Francisco, CA 94158-2261',
          'format' => NULL,
          'safe_value' => '1650 Owens Street San Francisco, CA 94158-2261',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1418952453,
    'title' => 'GIVING TO GLADSTONE',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Giving to Gladstone',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734312,
    'uuid' => 'f81766ee-5368-4c35-ace6-160deefd3fe4',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Our scientists are revealing 
the root causes of disease, 
and private philanthropy is 
making it possible.',
          'format' => 'rich_text',
          'safe_value' => '<p>Our scientists are revealing<br />
the root causes of disease,<br />
and private philanthropy is<br />
making it possible.</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'https://donation.towercare.com/gladstone-donation-form',
          'title' => 'Make a Gift',
          'attributes' => array(
            'class' => 'donate',
          ),
        ),
      ),
    ),
  );
  return $fpps;
}
