<?php
/**
 * @file
 * structure.features.uuid_fpp.inc
 */

/**
 * Implements hook_uuid_features_default_fpps().
 */
function structure_uuid_features_default_fpps() {
  $fpps = array();

  $fpps[] = array(
    'timestamp' => 1417733712,
    'title' => 'SCIENTIST SPOTLIGHT',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Scientist Spotlight',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417733712,
    'uuid' => '25f3cd3d-3153-4561-844d-b3ae9ffeee19',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => '<p><b>BENOIT BRUNEAU, PHD</b><br />
Mapping the heart, moving<br />
closer to heart disease cures</p>
',
          'format' => 'limited_html',
          'safe_value' => '<p><b>BENOIT BRUNEAU, PHD</b><br />
Mapping the heart, moving<br />
closer to heart disease cures</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734507,
    'title' => 'FEATURED VIDEO',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Featured Video',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734507,
    'uuid' => '430d4112-be9c-4653-956a-645ab9ddbf9c',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'BETTER COGNITION SEEN 
WITH GENE VARIANT 
CARRIED BY 1 IN 5',
          'format' => 'rich_text',
          'safe_value' => '<p>BETTER COGNITION SEEN<br />
WITH GENE VARIANT<br />
CARRIED BY 1 IN 5</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734598,
    'title' => 'OUR MISSION',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Our Mission',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734598,
    'uuid' => '6d4bd53f-a154-470d-8ed5-ccea06f9e0ca',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Use visionary science and 
technology to overcome
major unsolved diseases',
          'format' => 'rich_text',
          'safe_value' => '<p>Use visionary science and<br />
technology to overcome<br />
major unsolved diseases</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'node/10',
          'title' => 'LEARN MORE',
          'attributes' => array(
            'class' => '',
          ),
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734703,
    'title' => 'GET OUR NEWSLETTER',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Get Our Newsletter',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734677,
    'uuid' => '8ec939f2-35ae-4d63-929b-00c890ea51ab',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Important discoveries and 
insights, direct to your inbox',
          'format' => 'rich_text',
          'safe_value' => '<p>Important discoveries and<br />
insights, direct to your inbox</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734389,
    'title' => '',
    'log' => '',
    'bundle' => 'image',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Front page feature',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734389,
    'uuid' => '91b7243d-de5b-4eb2-a789-562a48273cbb',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:0:"";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(),
  );
  $fpps[] = array(
    'timestamp' => 1417733879,
    'title' => 'OUR SCIENCE',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Our Science',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417733879,
    'uuid' => 'c9a58689-7b2b-4f2d-8109-6b421f765214',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'file_rendered',
          'settings' => 'a:1:{s:14:"file_view_mode";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'focused on unsolved
diseases with profound
medical, economic, and
social impact',
          'format' => 'rich_text',
          'safe_value' => '<p>focused on unsolved<br />
diseases with profound<br />
medical, economic, and<br />
social impact</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'node/1',
          'title' => 'BRAIN',
          'attributes' => array(
            'class' => '',
          ),
        ),
        1 => array(
          'url' => 'node/2',
          'title' => 'HEART',
          'attributes' => array(
            'class' => '',
          ),
        ),
        2 => array(
          'url' => 'node/3',
          'title' => 'IMMUNESYSTEM',
          'attributes' => array(
            'class' => '',
          ),
        ),
        3 => array(
          'url' => 'node/4',
          'title' => 'STEM CELL',
          'attributes' => array(
            'class' => '',
          ),
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734856,
    'title' => 'LOREM IPSUM',
    'log' => '',
    'bundle' => 'text',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Lorem Ipsum',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734803,
    'uuid' => 'd6dbded7-1639-4f46-8cb6-32a0de08c7cc',
    'language' => 'und',
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => '<p>
&nbsp;<br />
&nbsp;<br />
&nbsp;<br />
&nbsp;<br />
&nbsp;<br />
</p>
',
          'format' => 'limited_html',
          'safe_value' => '<p>
 <br />
 <br />
 <br />
 <br />
 
</p>
',
        ),
      ),
    ),
  );
  $fpps[] = array(
    'timestamp' => 1417734312,
    'title' => 'GIVING TO GLADSTONE',
    'log' => '',
    'bundle' => 'jump_menu',
    'link' => 0,
    'path' => '',
    'reusable' => 1,
    'admin_title' => 'Giving to Gladstone',
    'admin_description' => '',
    'category' => 'Reusable Content',
    'view_access' => NULL,
    'edit_access' => NULL,
    'created' => 1417734312,
    'uuid' => 'f81766ee-5368-4c35-ace6-160deefd3fe4',
    'language' => 'und',
    'field_formatter' => array(
      'und' => array(
        0 => array(
          'type' => 'image',
          'settings' => 'a:2:{s:11:"image_style";s:21:"profile_picture_large";s:10:"image_link";s:0:"";}',
        ),
      ),
    ),
    'field_image' => array(),
    'field_longtext' => array(
      'und' => array(
        0 => array(
          'value' => 'Our scientists are revealing 
the root causes of disease, 
and private philanthropy is 
making it possible.',
          'format' => 'rich_text',
          'safe_value' => '<p>Our scientists are revealing<br />
the root causes of disease,<br />
and private philanthropy is<br />
making it possible.</p>
',
        ),
      ),
    ),
    'field_urls' => array(
      'und' => array(
        0 => array(
          'url' => 'node/3',
          'title' => 'MAKE A GIFT',
          'attributes' => array(
            'class' => 'donate',
          ),
        ),
      ),
    ),
  );
  return $fpps;
}
