<?php
/**
 * @file
 * Drupal needs this blank file.
 *
 * Statically defined migrations (w/o UI)
 * ---------------------------------------
 * Migrate operates almost entirely through classes, and by adding any
 * files containing class definitions to the .info file, those files 
 * are automatically included only when the classes they contain are 
 * referenced. The one non-class piece you need to implement is 
 * hook_migrate_api(), but because *.migrate.inc is registered using
 * hook_hook_info, by defining your implementation of that hook in
 * a_wusel_migration.migrate.inc, it is automatically invoked only 
 * when needed.
 *
 * source: https://www.drupal.org/node/1285276
 *
 *
 * Dynamically defined migrations (w/ ui)
 * --------------------------------------
 * Migrations that use different instances of the same base class to 
 * to migrate different content should use Dynamically registered 
 * migrations, here in the *.module file
 *
 */

function gladstone_migrate_flush_caches() {

	// Common arguments
	$args = array(
		'group_name' => 'Gladstone',
		'source_version' => 7,
		'source_connection' => 'legacy',
		'source_database' => array(
			'driver'   => 'mysql',
			'database' => variable_get('gladstone_migrate_source_schema',''),
			'username' => variable_get('gladstone_migrate_source_user',''),
			'password' => variable_get('gladstone_migrate_source_pass',''),
			'host'     => '127.0.0.1',
			'prefix'   => '',
		),
		'format_mappings' => array(
			'php' => 'full_html',
			'full_html' => 'full_html',
			'limited_html' => 'limited_html',
			'rich_text' => 'rich_text',
			'plain_text' => 'plain_text'
		)
	);

	// Register migrations -----
	Migration::registerMigration('GSFile','files',$args+array(
		'source_dir' => '/Users/jnand/Documents/Projects/gladstone/gladstone-web-d7/gladstone.org.git/htdocs/releases/20141006235547/builds/demo/sites/default/files',
		'destination_dir' => 'public://'
	));	
	Migration::registerMigration('GSOpsRoleTerms','operational_role', $args);
	Migration::registerMigration('GSOpsTitleTerms','operational_title', $args);
	Migration::registerMigration('GSInstitutionTerms','institution', $args);
	Migration::registerMigration('GSUser','user', $args);
	Migration::registerMigration('GSRole','role', $args);
	Migration::registerMigration('GSProfile','profile', $args);
	Migration::registerMigration('GSLeadership','leadership', $args);
	Migration::registerMigration('GSLeadershipLeadership','leadership_collection', $args);
	Migration::registerMigration('GSCurriculumVitae','curriculum_vitae', $args);
	Migration::registerMigration('GSCurriculumVitaeAffiliations','affiliation', $args);
	Migration::registerMigration('GSCurriculumVitaeEducation','education', $args);
	Migration::registerMigration('GSCurriculumVitaeProfTitles','prof_title', $args);
	Migration::registerMigration('GSEvent','event', $args);
	Migration::registerMigration('GSInTheNews','in_the_news', $args);
	Migration::registerMigration('GSNews','news', $args);
	Migration::registerMigration('GSPressRelease','press_release', $args);
	Migration::registerMigration('GSHonorsAndAwards','honors_and_award', $args);
	Migration::registerMigration('GSHonorsAndAwardsRelations','honors_and_awards_relation', $args);
	// ADD migration to update node_refs
}


