<?php
/**
 * @file
 * Code for the Base feature.
 */

include_once 'base.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function base_ctools_plugin_directory($module, $plugin) {

  if ($module == 'page_manager' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }

  return 'plugins/' . $plugin;
}

/**
 * Implements hook_date_formats().
 * @see http://thinkshout.com/blog/2014/05/custom-date-formats-in-drupal/
 */
function base_date_formats() {
  return array(
    // Creates a new format for a new, custom format type.
    array(
      'type' => 'article',
      'format' => 'F j, Y',
      'locales' => array(),
    ),
    array(
      'type' => 'year',
      'format' => 'Y',
      'locales' => array()
    )
  );
}

/**
 * Implements hook_date_format_types().
 */
function base_date_format_types() {
  return array(
    'article' => t('Month dd, YYYY'),
    'year' => t('YYYY')
  );
}