<?php
/**
 * @file
 * Code for the Honors and Awards feature.
 */


include_once 'honors_and_awards.features.inc';

/**
 * Implements hook_admin_paths_alter()
 */
function honors_and_awards_admin_paths_alter(&$paths) {
	// Add new path for "Edit" tab to show up when viewing a page managed node
	$paths['Honors and Awards/*/*/edit'] = TRUE;
	return $paths;
}

/**
 * Implements hook_menu_alter()
 */
function honors_and_awards_menu_alter(&$items) {
	$items['Honors and Awards/%/%node/edit'] = array(
		'title' => 'Edit',
		'description' => 'Edit page managed node',
		'page callback'  => 'node_page_edit',
		'page arguments' => array(2),
		'access callback' => 'node_access',
		'access arguments' => array('update',2),
		'type' => MENU_LOCAL_TASK,
		'context' => MENU_CONTEXT_PAGE,
		'tab_parent' => 'Honors and Awards/%/%',
		'tab_root' => 'Honors and Awards/%/%',
		'file' => 'node.pages.inc',
		'module' => 'node'
	);
}