<?php
/**
 * @file
 * Code for the Honors and Awards feature.
 */


include_once 'honors_and_awards.features.inc';


/**
 * Implements hook_views_query_alter(&$view, &$query)
 */
function honors_and_awards_views_query_alter(&$view, &$query) {

  // OR logic for context filters, so that we return nodes filtered by
  // a profile ops term of a node ops term
  if ($view->name == 'honors_and_awards') {
    $query->where[0]['type'] = 'OR';
  }
}