<?php
/**
 * @file
 * Module file for Classy Panel Styles.
 */

// Drupal variable: Location of the CSS file containing CPS class definitions.
const CLASSY_PANEL_STYLES_CSS_PATH  = 'classy_panel_styles__css_path';

// Drupal variable: Enable/Disable application of styles in the backend editor.
const CLASSY_PANEL_STYLES_EDITOR_STYLING = 'classy_panel_styles__editor_styling';

// Drupal variable: The base style to use when rendering regions.
const CLASSY_PANEL_STYLES_REGION_STYLE = 'classy_panel_styles__base_region_style';

// Bitmasks for the "Pane/Region/Both" value.
const CLASSY_PANEL_STYLES_PANE_MASK    = 1;
const CLASSY_PANEL_STYLES_REGION_MASK  = 2;

// Layout options.
const CLASSY_PANEL_STYLES_LAYOUTS_ALL     = 0;
const CLASSY_PANEL_STYLES_LAYOUTS_EXCLUDE = 1;
const CLASSY_PANEL_STYLES_LAYOUTS_INCLUDE = 2;

// Form element name for the custom class list.
const CLASSY_PANEL_STYLES_CUSTOM_CLASSES = 'cps_custom_classes';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Specifies the plugin directory for our ctools plugins.
 */
function classy_panel_styles_ctools_plugin_directory($module, $plugin) {
  if (($module == 'panels' && $plugin == 'styles') ||
      ($module == 'ctools' && $plugin == 'export_ui')) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_permission().
 */
function classy_panel_styles_permission() {
  return array(
    'administer classy panel styles' => array(
      'title' => t('Administer Classy Panel Styles'),
      'description' => t('Create new Classy Panel Styles and adjust module settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function classy_panel_styles_menu() {
  $items['admin/config/content/classy_panel_styles/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('classy_panel_styles_admin_settings_form'),
    'access arguments' => array('administer classy panel styles'),
    'file' => 'classy_panel_styles.admin.inc'    
  );
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Attaches custom CSS and javascript. Applies Classy Panel Styles to the page.
 */
function classy_panel_styles_form_panels_panel_context_edit_content_alter(&$form, &$form_state) {
  _classy_panel_styles_attach($form);
  _classy_panel_styles_apply_all($form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Attaches custom CSS and javascript. Applies Classy Panel Styles to the page.
 */
function classy_panel_styles_form_panelizer_edit_content_form_alter(&$form, &$form_state) {
  _classy_panel_styles_attach($form);
  _classy_panel_styles_apply_all($form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Attaches custom CSS and javascript. Applies Classy Panel Styles to the page.
 */
function classy_panel_styles_form_panels_ipe_edit_control_form_alter(&$form, $form_state) {
  _classy_panel_styles_attach($form);
  _classy_panel_styles_apply_all($form_state);
}

/**
 * Attaches our custom css and js to a form.
 *
 * @param array $form
 *   The Drupal Form API form array.
 */
function _classy_panel_styles_attach(array &$form) {
  // Add custom CSS file.
  $css_path = variable_get(CLASSY_PANEL_STYLES_CSS_PATH, FALSE);
  if ($css_path && file_exists($css_path)) {
    $form['#attached']['css'][] = $css_path;
  }

  // Get path to Classy Panel Styles module.
  $module_path = drupal_get_path('module', 'classy_panel_styles');

  // Attach admin CSS file.
  $form['#attached']['css'][]
    = $module_path . '/admin_styles/css/classy_panel_styles.admin.css';

  // Attach JS file.
  $form['#attached']['js'][] = $module_path . '/js/classy_panel_styles.js';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a custom submit handler to the panels "edit style settings" form.
 */
function classy_panel_styles_form_panels_edit_style_settings_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'classy_panel_styles_plugin_settings_form_submit';
}

/**
 * Custom submit handler for the panels "edit style settings" form.
 *
 * Updates Drupal.settings js variable with the latest Classy Panels styles.
 * This includes setting to "none" when classy panels is not in use.
 */
function classy_panel_styles_plugin_settings_form_submit($form, &$form_state) {
  // Update the Drupal.settings javascript object.
  _classy_panel_styles_apply_all($form_state);
}

/**
 * Applies Classy Panel Styles to backend Panels pages via Javascript.
 *
 * @param object $form_state
 *   The Panels display object that contains the style configuration.
 */
function _classy_panel_styles_apply_all($form_state) {
  // Don't apply styles if the setting is turned off.
  if (!variable_get(CLASSY_PANEL_STYLES_EDITOR_STYLING, TRUE)) {
    return;
  }

  // Get the display object.
  $display = $form_state['display'];

  // Get the renderer class.
  $renderer_class = get_class($form_state['renderer']);

  // Add pane style settings to the Drupal.settings javascript object.
  foreach ($display->content as $pid => $pane) {
    // Make sure we actually have a pane.
    if (empty($pane->pid)) {
      continue;
    }
    $style = isset($pane->style, $pane->style['style']) ? $pane->style['style'] : NULL;
    $conf  = isset($pane->style, $pane->style['settings']) ? $pane->style['settings'] : array();
    _classy_panel_styles_apply('pane', $pid, $style, $conf, $renderer_class);
  }

  // Get shortcuts to the data we'll need below.
  $panel_settings = $display->panel_settings;
  $style_settings = $panel_settings['style_settings'];

  // Get the default style settings (set on the display object).
  $display_style
    = isset($panel_settings['style']) ? $panel_settings['style'] : NULL;
  $display_settings
    = isset($style_settings['default']) ? $style_settings['default'] : array();

  // Remove default settings from the list.
  unset($style_settings['default']);

  // Add region style settings to the Drupal.settings JS object.
  foreach ($style_settings as $name => $region_settings) {
    $style = isset($panel_settings[$name], $panel_settings[$name]['style']) ? $panel_settings[$name]['style'] : $display_style;
    $conf  = isset($region_settings) ? $region_settings : $display_settings;
    _classy_panel_styles_apply('region', $name, $style, $conf, $renderer_class);
  }
}

/**
 * Adds Classy Panel Styles to the Drupal.settings javascript object.
 *
 * @param string $type
 *   One of 'pane' or 'region'.
 * @param mixed $item_id
 *   Pane ID (int) or Region ID (string).
 * @param string $style
 *   The name of the currently selected style.
 * @param array $conf
 *   The associative array of style settings.
 */
function _classy_panel_styles_apply($type, $item_id, $style = NULL, array $conf = array(), $renderer_class = 'panels_renderer_editor') {
  // Calculate the HTML id of the region/pane div in the markup.
  switch ($type) {
    case 'pane':
      switch ($renderer_class) {
        // Standard editor.
        case 'panels_renderer_editor':
          $id = 'panel-pane-' . $item_id;
          break(2);

        // IPE.
        case 'panels_renderer_ipe':
          $id = 'panels-ipe-paneid-' . $item_id;
          break(2);

        default:
          // If neither IPE nor standard editor, do nothing.
          return;
      }

    case 'region':
      switch ($renderer_class) {
        // Standard editor.
        case 'panels_renderer_editor':
          $id = 'panel-region-' . $item_id;
          break(2);

        // IPE.
        case 'panels_renderer_ipe':
          $id = 'panels-ipe-regionid-' . $item_id;
          break(2);

        default:
          // If neither IPE nor standard editor, do nothing.
          return;
      }

    default:
      // If not a pane or region, don't do anything.
      return;
  }

  // Calculate the parent style name from the concatenated parent:substyle name.
  if ($pos = strpos($style, ':')) {
    $style = substr($style, 0, $pos);
  }

  // Get the array of classes to add. If not using classy_panel_styles, send an
  // empty array to clear any previously applied classy_panel_styles classes.
  $classes = 'classy_panel_styles' === $style ? _classy_panel_styles_filter_conf($conf) : array();

  // Add to the Drupal.settings object. Note that subsequent (ajax) calls have
  // some wonky behavior... When adding a value for an existing element, it
  // neither replaces nor merges: Your element will turn into an array with
  // two subelements, both of which have the new value. And no matter how many
  // times you call it, the element always has exactly two subelements.
  drupal_add_js(
    array(
      'classyPanels' => array(
        $id => implode(' ', $classes),
      ),
    ),
    'setting'
  );
}

/**
 * Filters out disabled CPS styles.
 *
 * @param array $conf
 *   The CPS settings configuration array.
 *
 * @return array
 *   The array of classes with disabled and empty ones removed.
 */
function _classy_panel_styles_filter_conf(array $conf) {
  ctools_include('export');
  $styles  = ctools_export_load_object('classy_panel_styles');
  $classes = array();
  foreach ($conf as $cps_id => $class) {
    // Don't add the class if the CPS style setting is disabled.
    if (!empty($class) && empty($styles[$cps_id]->disabled)) {
      $classes[] = check_plain($class);
    }
  }
  return $classes;
}

/**
 * Implements hook_theme_registry_alter().
 *
 * By using our own theme hook to mimic the default Panels pane theme hook, we
 * avoid unnecessary markup (one less div). It's also slightly faster.
 */
function classy_panel_styles_theme_registry_alter(&$theme_registry) {
  // Get a shortcut to our entry.
  $cps = &$theme_registry['classy_panel_styles_render_pane'];

  // Temporary storage for the functions we want to keep.
  $preprocess = $cps['preprocess functions'];
  $process    = $cps['process functions'];

  // Make our entry identical to the entry for Panels panes.
  $cps = $theme_registry['panels_pane'];

  // Add our functions back in.
  $cps['preprocess functions']
    = array_unique(array_merge($cps['preprocess functions'], $preprocess));
  $cps['process functions']
    = array_unique(array_merge($cps['process functions'], $process));
}
