<?php
/**
 * @file
 * Code for the Gladstone Admin feature.
 */

include_once 'gladstone_admin.features.inc';


/**
 * Implements hook_preprocess_html().
 */
function gladstone_admin_preprocess_html(&$variables) {

  // Add conditional stylesheets for admin pages on admin theme.	
  if ( path_is_admin(current_path()) ) {
    // reference current admin theme  
    $theme_path = drupal_get_path('theme', 'rubik');
    // reference module stylesheet    
    drupal_add_css(drupal_get_path('module', 'gladstone_admin') . '/stylesheets/gladstone_admin.css', array('weight' => CSS_THEME));
  }
}

/**
 * Implements hook_init()
 */
function gladstone_admin_init() {
  
  // Load the seven theme CSS for the media browser. This is done
  // because the seven theme may not be the admin theme, but the
  // media browser assumes that it is....
  if (arg(0) == 'media' && arg(1) == 'browser' && $GLOBALS['theme'] != 'seven') {
    $path = drupal_get_path('theme', 'seven');
    drupal_add_css($path.'/reset.css', array('basename' => 'seven_reset', 'group' => CSS_THEME));
    drupal_add_css($path.'/style.css', array('basename' => 'seven_style', 'group' => CSS_THEME));  
  }

}

/**
 * Implements hook_menu_local_tasks_alter()
 */
function gladstone_admin_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  /** Force Task "Tabs" To show for when editing page manager pages **/
  if (user_is_logged_in()) { 
  // Dont alter the admin page tabs
    if(path_is_admin(current_path())) return;

    // hack for admin of page manager pages
    if ( $router_item['page_callback'] = 'page_manager_page_execute' && array_key_exists(0, $data['tabs']) ) {
     $data['tabs']['0']['count'] =   $data['tabs']['0']['count'] + 1;
    }
  }
  
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * types of plugins: layouts, styles, args, contexts, content_types.
 */
function gladstone_admin_ctools_plugin_directory($owner, $plugin_type) {
  // We're just providing layout plugins.
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    return "plugins/$plugin_type";
  }
}