<?php


/**
 * Implements hook_preprocess_html().
 */
function gladstone_admin_preprocess_html(&$variables) {

  // Add conditional stylesheets for admin pages on admin theme.	
  if ( path_is_admin(current_path()) ) {
    // reference current admin theme  
    $theme_path = drupal_get_path('theme', 'rubik');
    // reference module stylesheet    
    drupal_add_css(drupal_get_path('module', 'gladstone_admin') . '/stylesheets/gladstone_admin.css', array('weight' => CSS_THEME));
  }
}


/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * types of plugins: layouts, styles, args, contexts, content_types.
 */
function gladstone_admin_ctools_plugin_directory($owner, $plugin_type) {
  // We're just providing layout plugins.
  if ($owner == 'panels' && $plugin_type == 'layouts') {
    return "plugins/$plugin_type";
  }
}